settings:
    legacy:
      force: false
      interval: 0s
schema:
    - name: app
      path: .
      commands:
        install:
          status: true
          method: go build -o ./app ./main.go
        # build:
        #   status: true
        #   method: go build -o ./app ./main.go
        run:
          status: true
          method: ./app
      watcher:
        extensions:
          - go
          - yml
          - html
        paths:
          - /
        ignored_paths:
          - .git
          - .realize