settings:
    legacy:
      force: false
      interval: 0s
schema:
    - name: app
      path: .
      commands:
        install:
          status: true
          method: go build -o /build/server ./web/server.go
        run:
          status: true
          method: /build/server
      watcher:
        extensions:
          - go
          - yml
          - html
        paths:
          - /
        ignored_paths:
          - .git
          - .realize