version: '3.5'
services: 
    app:
        container_name: "app"
        build:
            context: .
            dockerfile: ./Dockerfile.golang
            target: hotreload
        # ローカルからコンテナへのファイル群の受け渡し
        volumes: 
            - .:/go/src/todo_api
        working_dir: /go/src/todo_api
        command: realize start --name='app' --run
        # Herokuデプロイに対応したため環境変数PORTを定義する必要がある
        environment: 
            - PORT=8080
        ports: 
            - 8080:8080
        tty: true
        restart: always