version: '3.5'
services: 
    app:
        container_name: "golang_api"
        build:
            context: .
            dockerfile: ./Dockerfile.golang
        # ローカルからコンテナへのファイル群の受け渡し
        volumes: 
            - .:/go/src/todo_api
        working_dir: /go/src/todo_api
        command: realize start --name='app' --run
        # env_fileを指定しなければ.envから読み取った値を元にして環境変数を設定される
        env_file: 
            - ./.env.local
        ports: 
            - 8080:8080
        tty: true
        depends_on: 
            - mysql
        restart: always
    mysql:
        # コンテナ名を変えたら`.env.local`の`LOCAL_DB_HOST`も変える
        container_name: "mysql_db"
        image: mysql:8.0
        ports: 
            - 3306:3306
        volumes: 
            # 初期データを投入するSQLが格納されているdir
            - ./db/mysql_init:/docker-entrypoint-initdb.d
            # 永続化するときにマウントするdir
            - ./db/mysql_data:/var/lib/mysql
            # mysql8.0対応
            - ./db/mysql_conf/:/etc/mysql/conf.d
        env_file: 
            - ./.env.local
        restart: always