version: '3.5'
services: 
    app:
        build:
            context: .
            dockerfile: Dockerfile
            target: builder
        command: go run main.go
        #command: realize start --run --no-config
        environment: 
            - PORT=8080
        ports: 
            - 8080:8080
        container_name: "app"
        tty: true
        volumes: 
            - .:/go/src/app